[package]
name = "zproto"
version = "0.1.0"
authors = ["Stephen Hunt <stphnhnt.git@gmail.com>"]
edition = "2021"
description = "A library from communicating with Zaber products in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/stphnt/zproto"
documentation = "https://docs.rs/zproto"
homepage = "https://github.com/stphnt/zproto"
keywords = ["Zaber", "ASCII", "Binary", "serial", "RS232"]
categories = []

[dependencies]
log = "0.4"
nom = "7.1"
paste = "1.0"
serialport = "4.0"

[dev-dependencies]
simple_logger = "2.1"
static_assertions = "1.1"
trybuild = "1.0"
