[package]
name = "zproto"
version = "0.1.1"
authors = ["Stephen Hunt <stphnhnt.git@gmail.com>"]
edition = "2021"
description = "A library from communicating with Zaber products in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/stphnt/zproto"
documentation = "https://docs.rs/zproto"
homepage = "https://github.com/stphnt/zproto"
keywords = ["Zaber", "ASCII", "Binary", "serial", "RS232"]
categories = []

[package.metadata.docs.rs]
all-features = true

[features]
default = ["ascii", "binary"]
# Include the ASCII protocol
ascii = []
# Include the Binary protocol
binary = []

# Use the nightly-only `doc_cfg` feature when generating the documentation.
doc_cfg = []

[dependencies]
log = "0.4"
paste = "1.0"
serialport = "4.0"

[dev-dependencies]
simple_logger = "2.1"
static_assertions = "1.1"
trybuild = "1.0"

[[example]]
name = "ascii"
required-features = ["ascii"]

[[example]]
name = "binary"
required-features = ["binary"]
