---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
import: 
  - '@cspell/dict-rust/cspell-ext.json'
dictionaryDefinitions:
  - name: project-words
    path: './.cspell/project-words.txt'
  - name: zaber-words
    path: './.cspell/zaber-words.txt'
  - name: rust-libs
    path: './.cspell/rust-libs.txt'
dictionaries:
  - en-gb
  - project-words
  - zaber-words
  - rust-libs
ignorePaths:
  - 'target'
  - '.cspell'
  - '.github'
