name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - name: Install libudev
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libudev-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo check --all-features

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - name: Install libudev
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libudev-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --features=ascii,binary --workspace --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libudev
        run: |
          sudo apt update
          sudo apt install libudev-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy --all-features -- -D warnings

  spelling:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: crate-ci/typos@master

  doc:
    name: Rustdoc
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - name: Install libudev
        run: |
          sudo apt update
          sudo apt install libudev-dev
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-docs
      - uses: Swatinem/rust-cache@v1
      - run: cargo doc --no-deps --all-features
